default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kaddisto_airways_dev

test:
  <<: *default
  database: kaddisto_airways_test

production:
  <<: *default
  database: kaddisto_airways_prod